version: "3"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8000:8000
    command: npm run start:dev
    depends_on:
      - books-home-db
      - redis
    environment:
      - HOST=localhost
      - PORT=8000
      - SECRET_KEY=secretKey
      - AWS_REGION=ams3
      - AWS_S3BUCKET=bookshome
      - AWS_ENDPOINT=ams3.digitaloceanspaces.com
      - AWS_ACCESS_KEY_ID=4BRZT5RLVA7JA343MH6Y
      - AWS_SECRET_ACCESS_KEY=52Ew5C6OXp2OvWJTd0+9JtUXin7G8i8i6Y741gnM2T8
      - MONGODB_URL=mongodb://books-home-db:27017/books-home
      - FRONTEND_URL=localhost
      - FRONTEND_PORT=3000
      - DASHBOARD_URL=localhost
      - DASHBOARD_PORT=5000
    restart: always

  books-home-db:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="books-home"
    ports:
      - 27017:27017

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.108.0.1/16